### ISSUE TITLE
Can't find variable accordion 

### ISSUE THREAD

**Issue by TeodorKolev** [angularify/angular-semantic-ui#15]
Can't find variable accordion at src/accordion/accordion.js : 3

**Comment by jspdown** [comment]
Could you give us a description on how to reproduce this error. It works great for me:
![screen shot 2015-03-15 at 11 12 54 am](https://cloud.githubusercontent.com/assets/2843268/6655340/953dca98-cb04-11e4-8729-254b21b26fb5.png)

**Comment by 0xAX** [comment]
@jspdown btw, thank you for contribution. Unforutantelly i have no time for angular-semantic-ui developent, Would you like i will add you to this project.

**Comment by jspdown** [comment]
Thanks @0xAX , I'm using angular-semantic-ui for a side project and I need to fix/add feature for that. I really want to invest myself in an open-source project. So, I can help for reviews and merges...

**Comment by 0xAX** [comment]
thank you @jspdown, sent invite to the angularify group
