### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by Ehesp** [angularify/angular-semantic-ui#23]
Hello,

On the Semanic UI site, the modal for example zooms and fades in:

http://semantic-ui.com/modules/modal.html

On the angular example, the modal just appears instantly:

http://angularify.github.io/angular-semantic-ui/templates/modal.html

Is there anyway to animate this?
Cheers

**Comment by jspdown** [comment]
I think we should animate it by default, everybody wants it like that. 
To animate it we have to add `.modal('setting', 'transition', value)` in the directive.
