### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by majimboo** [angularify/angular-semantic-ui#9]
make it installable via bower.

**Comment by JohnSmithX** [comment]
good

**Comment by iamtankist** [comment]
Please correct the urls in the bower.json to point to your own repository, not the fork.

**Comment by KapuzenSohn** [comment]
Please correct the main Files in the bower.json

As a Quick fix:
```
"overrides": {
"angular-semantic-ui": {
"main": [
"dist/angular-semantic-ui-0.0.1.js"
]
}
```

Insert this in your main bower.json File and everything will load fine

**Comment by jspdown** [comment]
Why `dist/angular-semantic-ui-0.0.1.js`?
Grunt generate `angular-semantic-ui.js`.

**Comment by KapuzenSohn** [comment]
Wenn I look in the bower Folder and then under dist there is a File namend ```angular-semantic-ui-0.0.1.js```

**Comment by jspdown** [comment]
Ok, now I see where the problem come from. We didn't published the package to bower since a while. So the bower version of `angular-semantic-ui` is not up to date. 
I will publish the new version.

Thanks @KapuzenSohn

**Comment by KapuzenSohn** [comment]
Oh okay
